### PR TITLE
Update readme to reference proper image

### PR DESCRIPTION
**Pull request by theworkflow**
Make update in the readme to reference the correct
docker image for others to pull. Docker image
name has been updated and this will now reflect
the name change

### CODE REVIEW

**Comment by fiveisprime** [comment]
I thought we were removing `image` and `docker` from the image names.

**Comment by theworkflow** [comment]
As of right now the image the image that's published to docker hub is `onmodulus/basimage`. There are also other PRs that make the same reference. 

DockerHub Image --> https://hub.docker.com/r/onmodulus/baseimage/
Name Reference --> https://github.com/onmodulus/docker-build-base/pull/2/files

**Comment by jackboberg** [comment]
:+1:

**Comment by theworkflow** [comment]
We voted to _not_ have tagged version in the README under the example usage section

**Pull request merged**
