### PR TITLE
Remove openssh client last

### PR DESCRIPTION
**Pull request by kenXengineering**
This commit will remove the openssh server, client and sftp server from the base image.  The remove for the openssh-client is the second to last item to ensure it is removed.

### CODE REVIEW

**Comment by jackboberg** [comment]
Can you clarify why they need to be separate?

**Comment by kenXengineering** [comment]
I was having issues getting openssh-client to remove after building the image.  I tested removing the client, server, and sft-server as the second to last step and it worked.  Combined into one line.

**Comment by jackboberg** [comment]
:+1:

**Comment by tzmanics** [comment]
👍

**Pull request merged**
